import type { Product, Review } from './types';

export const mockReviews: Review[] = [
  {
    id: 'review-1',
    vendorId: 'vendor-1',
    vendorName: 'Super Tacos',
    rating: 5,
    comment: 'These onions are always fresh and crisp. The price is unbeatable for this quality.',
    date: '2023-10-20',
  },
  {
    id: 'review-2',
    vendorId: 'vendor-2',
    vendorName: 'Mumbai Bites',
    rating: 4,
    comment: 'Good quality, but I wish they offered a slightly lower price for bulk orders. Still, very reliable.',
    date: '2023-10-18',
  },
  {
    id: 'review-3',
    vendorId: 'vendor-3',
    vendorName: 'Pizza Corner',
    rating: 3,
    comment: 'The quality can be inconsistent. Last batch was great, this one not so much. The cost keeps me coming back though.',
    date: '2023-10-15',
  },
  {
    id: 'review-4',
    vendorId: 'vendor-4',
    vendorName: 'Curry Up',
    rating: 5,
    comment: 'Fantastic quality potatoes. They make the best fries. The cost is a little high, but worth it for the premium product.',
    date: '2023-10-22',
  },
   {
    id: 'review-5',
    vendorId: 'vendor-5',
    vendorName: 'Noodle House',
    rating: 2,
    comment: 'The delivery was late and the vegetables were not as fresh as promised. The low price is the only plus.',
    date: '2023-10-21',
  },
];


export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Fresh Red Onions',
    category: 'Food',
    price: 15.99,
    quantity: 100,
    availability: true,
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'red onions',
    supplierId: 'sup-1',
    supplierName: 'FarmFresh Co.',
    description: 'Crisp, high-quality red onions, perfect for salads, grilling, and cooking. Sourced from local farms.',
    reviews: mockReviews,
    rating: 4.5,
  },
  {
    id: 'prod-2',
    name: 'Premium Cooking Oil',
    category: 'Food',
    price: 45.5,
    quantity: 50,
    availability: true,
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'cooking oil',
    supplierId: 'sup-1',
    supplierName: 'FarmFresh Co.',
    description: 'Versatile and healthy cooking oil, ideal for frying and sautéing. Comes in a large 5-liter container.',
    reviews: mockReviews.slice(1,3),
    rating: 4.2,
  },
  {
    id: 'prod-7',
    name: 'Ballpoint Pens (Box of 50)',
    category: 'Stationery',
    price: 12.00,
    quantity: 150,
    availability: true,
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'ballpoint pens',
    supplierId: 'sup-4',
    supplierName: 'Office Essentials',
    description: 'A box of 50 blue ink ballpoint pens with a comfortable grip. Perfect for daily use.',
    reviews: [],
    rating: 0,
  },
  {
    id: 'prod-8',
    name: 'Disposable Paper Plates (100 pack)',
    category: 'Packaging',
    price: 8.50,
    quantity: 300,
    availability: true,
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'paper plates',
    supplierId: 'sup-1',
    supplierName: 'FarmFresh Co.',
    description: 'Pack of 100 sturdy and eco-friendly disposable paper plates, ideal for serving snacks and meals.',
    reviews: [mockReviews[0]],
    rating: 5,
  },
  {
    id: 'prod-9',
    name: 'All-Purpose Cleaner',
    category: 'Cleaning',
    price: 18.75,
    quantity: 75,
    availability: true,
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'cleaning spray',
    supplierId: 'sup-4',
    supplierName: 'Office Essentials',
    description: 'A powerful all-purpose cleaner for various surfaces. 1-gallon container.',
    reviews: [],
    rating: 0,
  },
  {
    id: 'prod-10',
    name: 'Assam Tea Leaves (1kg)',
    category: 'Beverage',
    price: 22.00,
    quantity: 90,
    availability: false,
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'tea leaves',
    supplierId: 'sup-2',
    supplierName: 'Golden Grains',
    description: '1kg bag of premium Assam tea leaves, known for its strong and malty flavor.',
    reviews: mockReviews.slice(2,4),
    rating: 4.1,
  },
  {
    id: 'prod-3',
    name: 'Organic All-Purpose Flour',
    category: 'Food',
    price: 25.0,
    quantity: 200,
    availability: true,
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'flour bag',
    supplierId: 'sup-2',
    supplierName: 'Golden Grains',
    description: 'High-quality organic flour for all your baking needs. 10kg bag.',
    reviews: mockReviews.slice(0,2),
    rating: 4.8,
  },
  {
    id: 'prod-4',
    name: 'Idaho Potatoes',
    category: 'Food',
    price: 22.0,
    quantity: 80,
    availability: false,
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'potatoes sack',
    supplierId: 'sup-1',
    supplierName: 'FarmFresh Co.',
    description: 'Bulk bag of versatile Idaho potatoes, great for fries, mashing, or baking. 20kg sack.',
    reviews: mockReviews.slice(3,5),
    rating: 4.6,
  },
  {
    id: 'prod-5',
    name: 'Free-Range Chicken Breast',
    category: 'Food',
    price: 80.0,
    quantity: 30,
    availability: true,
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'raw chicken',
    supplierId: 'sup-3',
    supplierName: 'Quality Meats',
    description: 'Tender, juicy, and ethically sourced free-range chicken breasts. Sold per 5kg pack.',
    reviews: [],
    rating: 0,
  },
  {
    id: 'prod-6',
    name: 'San Marzano Tomatoes',
    category: 'Food',
    price: 35.0,
    quantity: 60,
    availability: true,
    imageUrl: 'https://placehold.co/400x400.png',
    imageHint: 'canned tomatoes',
    supplierId: 'sup-2',
    supplierName: 'Golden Grains',
    description: 'Canned San Marzano tomatoes, the gold standard for authentic Italian sauces. Case of 12 cans.',
    reviews: [mockReviews[0]],
    rating: 5,
  },
];
