import type { Product, Review } from './types';

export const mockReviews: Review[] = [
  {
    id: 'review-1',
    vendorId: 'vendor-1',
    vendorName: 'Super Tacos',
    rating: 5,
    comment: 'These onions are always fresh and crisp. The price is unbeatable for this quality.',
    date: '2023-10-20',
  },
  {
    id: 'review-2',
    vendorId: 'vendor-2',
    vendorName: 'Mumbai Bites',
    rating: 4,
    comment: 'Good quality, but I wish they offered a slightly lower price for bulk orders. Still, very reliable.',
    date: '2023-10-18',
  },
  {
    id: 'review-3',
    vendorId: 'vendor-3',
    vendorName: 'Pizza Corner',
    rating: 3,
    comment: 'The quality can be inconsistent. Last batch was great, this one not so much. The cost keeps me coming back though.',
    date: '2023-10-15',
  },
  {
    id: 'review-4',
    vendorId: 'vendor-4',
    vendorName: 'Curry Up',
    rating: 5,
    comment: 'Fantastic quality potatoes. They make the best fries. The cost is a little high, but worth it for the premium product.',
    date: '2023-10-22',
  },
   {
    id: 'review-5',
    vendorId: 'vendor-5',
    vendorName: 'Noodle House',
    rating: 2,
    comment: 'The delivery was late and the vegetables were not as fresh as promised. The low price is the only plus.',
    date: '2023-10-21',
  },
];


export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Fresh Red Onions',
    category: 'Vegetables',
    price: 15.99,
    quantity: 100,
    availability: true,
    imageUrl: 'https://placehold.co/600x400.png',
    supplierId: 'sup-1',
    supplierName: 'FarmFresh Co.',
    description: 'Crisp, high-quality red onions, perfect for salads, grilling, and cooking. Sourced from local farms.',
    reviews: mockReviews,
    rating: 4.5,
  },
  {
    id: 'prod-2',
    name: 'Premium Cooking Oil',
    category: 'Pantry',
    price: 45.5,
    quantity: 50,
    availability: true,
    imageUrl: 'https://placehold.co/600x400.png',
    supplierId: 'sup-1',
    supplierName: 'FarmFresh Co.',
    description: 'Versatile and healthy cooking oil, ideal for frying and sautéing. Comes in a large 5-liter container.',
    reviews: mockReviews.slice(1,3),
    rating: 4.2,
  },
  {
    id: 'prod-3',
    name: 'Organic All-Purpose Flour',
    category: 'Pantry',
    price: 25.0,
    quantity: 200,
    availability: true,
    imageUrl: 'https://placehold.co/600x400.png',
    supplierId: 'sup-2',
    supplierName: 'Golden Grains',
    description: 'High-quality organic flour for all your baking needs. 10kg bag.',
    reviews: mockReviews.slice(0,2),
    rating: 4.8,
  },
  {
    id: 'prod-4',
    name: 'Idaho Potatoes',
    category: 'Vegetables',
    price: 22.0,
    quantity: 80,
    availability: false,
    imageUrl: 'https://placehold.co/600x400.png',
    supplierId: 'sup-1',
    supplierName: 'FarmFresh Co.',
    description: 'Bulk bag of versatile Idaho potatoes, great for fries, mashing, or baking. 20kg sack.',
    reviews: mockReviews.slice(3,5),
    rating: 4.6,
  },
  {
    id: 'prod-5',
    name: 'Free-Range Chicken Breast',
    category: 'Meat',
    price: 80.0,
    quantity: 30,
    availability: true,
    imageUrl: 'https://placehold.co/600x400.png',
    supplierId: 'sup-3',
    supplierName: 'Quality Meats',
    description: 'Tender, juicy, and ethically sourced free-range chicken breasts. Sold per 5kg pack.',
    reviews: [],
    rating: 0,
  },
  {
    id: 'prod-6',
    name: 'San Marzano Tomatoes',
    category: 'Vegetables',
    price: 35.0,
    quantity: 60,
    availability: true,
    imageUrl: 'https://placehold.co/600x400.png',
    supplierId: 'sup-2',
    supplierName: 'Golden Grains',
    description: 'Canned San Marzano tomatoes, the gold standard for authentic Italian sauces. Case of 12 cans.',
    reviews: [mockReviews[0]],
    rating: 5,
  },
];
