
import type { Product, Review, User } from './types';

export const mockReviews: Review[] = [
  {
    id: 'review-1',
    vendorId: 'vendor-1',
    vendorName: 'Super Tacos',
    rating: 5,
    comment: 'These onions are always fresh and crisp. The price is unbeatable for this quality.',
    date: '2023-10-20',
  },
  {
    id: 'review-2',
    vendorId: 'vendor-2',
    vendorName: 'Mumbai Bites',
    rating: 4,
    comment: 'Good quality, but I wish they offered a slightly lower price for bulk orders. Still, very reliable.',
    date: '2023-10-18',
  },
  {
    id: 'review-3',
    vendorId: 'vendor-3',
    vendorName: 'Pizza Corner',
    rating: 3,
    comment: 'The quality can be inconsistent. Last batch was great, this one not so much. The cost keeps me coming back though.',
    date: '2023-10-15',
  },
  {
    id: 'review-4',
    vendorId: 'vendor-4',
    vendorName: 'Curry Up',
    rating: 5,
    comment: 'Fantastic quality potatoes. They make the best fries. The cost is a little high, but worth it for the premium product.',
    date: '2023-10-22',
  },
   {
    id: 'review-5',
    vendorId: 'vendor-5',
    vendorName: 'Noodle House',
    rating: 2,
    comment: 'The delivery was late and the vegetables were not as fresh as promised. The low price is the only plus.',
    date: '2023-10-21',
  },
];


export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Fresh Red Onions',
    category: 'Food',
    price: 15.99,
    quantity: 100,
    availability: true,
    imageUrl: 'https://images.unsplash.com/photo-1642582037312-9b9639be89e6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyMHx8RnJlc2glMjBSZWQlMjBPbmlvbnN8ZW58MHx8fHwxNzUzNjM0OTI3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'fresh onions',
    supplierId: 'sup-1',
    supplierName: 'FarmFresh Co.',
    description: 'Crisp, high-quality red onions, perfect for salads, grilling, and cooking. Sourced from local farms.',
    reviews: mockReviews,
    rating: 4.5,
  },
  {
    id: 'prod-2',
    name: 'Premium Cooking Oil',
    category: 'Food',
    price: 45.5,
    quantity: 50,
    availability: true,
    imageUrl: 'https://images.unsplash.com/photo-1652282556241-0ce13285d00f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMnx8UHJlbWl1bSUyMENvb2tpbmclMjBPaWwlMjB8ZW58MHx8fHwxNzUzNjM0OTgwfDA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'oil bottle',
    supplierId: 'sup-1',
    supplierName: 'FarmFresh Co.',
    description: 'Versatile and healthy cooking oil, ideal for frying and sautéing. Comes in a large 5-liter container.',
    reviews: mockReviews.slice(1,3),
    rating: 4.2,
  },
  {
    id: 'prod-3',
    name: 'Organic All-Purpose Flour',
    category: 'Food',
    price: 25.0,
    quantity: 200,
    availability: true,
    imageUrl: 'https://images.unsplash.com/photo-1627485937980-221c88ac04f9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxN3x8T3JnYW5pYyUyMEFsbC1QdXJwb3NlJTIwRmxvdXJ8ZW58MHx8fHwxNzUzNjM0ODM1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'flour sack',
    supplierId: 'sup-2',
    supplierName: 'Golden Grains',
    description: 'High-quality organic flour for all your baking needs. 10kg bag.',
    reviews: mockReviews.slice(0,2),
    rating: 4.8,
  },
  {
    id: 'prod-4',
    name: 'Idaho Potatoes',
    category: 'Food',
    price: 22.0,
    quantity: 80,
    availability: false,
    imageUrl: 'https://images.unsplash.com/photo-1694393779439-11ff6dbad2a4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxJZGFobyUyMFBvdGF0b2VzfGVufDB8fHx8MTc1MzYzNDg2M3ww&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'potatoes crate',
    supplierId: 'sup-1',
    supplierName: 'FarmFresh Co.',
    description: 'Bulk bag of versatile Idaho potatoes, great for fries, mashing, or baking. 20kg sack.',
    reviews: mockReviews.slice(3,5),
    rating: 4.6,
  },
  {
    id: 'prod-5',
    name: 'Free-Range Chicken Breast',
    category: 'Food',
    price: 80.0,
    quantity: 30,
    availability: true,
    imageUrl: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxGcmVlLVJhbmdlJTIwQ2hpY2tlbiUyMEJyZWFzdHxlbnwwfHx8fDE3NTM2MzUxODh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'raw chicken',
    supplierId: 'sup-3',
    supplierName: 'Quality Meats',
    description: 'Tender, juicy, and ethically sourced free-range chicken breasts. Sold per 5kg pack.',
    reviews: [],
    rating: 0,
  },
  {
    id: 'prod-6',
    name: 'San Marzano Tomatoes',
    category: 'Food',
    price: 35.0,
    quantity: 60,
    availability: true,
    imageUrl: 'https://images.unsplash.com/photo-1694447970632-1323ac203eee?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMXx8U2FuJTIwTWFyemFubyUyMFRvbWF0b2VzfGVufDB8fHx8MTc1MzYyNDE1Nnww&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'tomato can',
    supplierId: 'sup-2',
    supplierName: 'Golden Grains',
    description: 'Canned San Marzano tomatoes, the gold standard for authentic Italian sauces. Case of 12 cans.',
    reviews: [mockReviews[0]],
    rating: 5,
  },
  {
    id: 'prod-7',
    name: 'Ballpoint Pens (Box of 50)',
    category: 'Stationery',
    price: 12.00,
    quantity: 150,
    availability: true,
    imageUrl: 'https://images.unsplash.com/photo-1560806863-6ccdecaf1dc5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxCYWxscG9pbnQlMjBQZW5zJTIwJTI4Qm94JTIwb2YlMjA1MCUyOXxlbnwwfHx8fDE3NTM2MzUyNjl8MA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'pen box',
    supplierId: 'sup-4',
    supplierName: 'Office Essentials',
    description: 'A box of 50 blue ink ballpoint pens with a comfortable grip. Perfect for daily use.',
    reviews: [],
    rating: 0,
  },
  {
    id: 'prod-8',
    name: 'Disposable Paper Plates (100 pack)',
    category: 'Packaging',
    price: 8.50,
    quantity: 300,
    availability: true,
    imageUrl: 'https://images.unsplash.com/photo-1609779495137-8096e4534abe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxNXx8RGlzcG9zYWJsZSUyMFBhcGVyJTIwUGxhdGVzfGVufDB8fHx8MTc1MzYyNDAxN3ww&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'paper plates',
    supplierId: 'sup-1',
    supplierName: 'FarmFresh Co.',
    description: 'Pack of 100 sturdy and eco-friendly disposable paper plates, ideal for serving snacks and meals.',
    reviews: [mockReviews[0]],
    rating: 5,
  },
  {
    id: 'prod-9',
    name: 'All-Purpose Cleaner',
    category: 'Cleaning',
    price: 18.75,
    quantity: 75,
    availability: true,
    imageUrl: 'https://images.unsplash.com/photo-1587937533577-0ba337fbd436?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxBbGwtUHVycG9zZSUyMENsZWFuZXJ8ZW58MHx8fHwxNzUzNjM1Mjk4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'cleaning spray',
    supplierId: 'sup-4',
    supplierName: 'Office Essentials',
    description: 'A powerful all-purpose cleaner for various surfaces. 1-gallon container.',
    reviews: [],
    rating: 0,
  },
  {
    id: 'prod-10',
    name: 'Assam Tea Leaves (1kg)',
    category: 'Beverage',
    price: 22.00,
    quantity: 90,
    availability: false,
    imageUrl: 'https://images.unsplash.com/photo-1628153792464-21bffac488d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxUZWElMjBsZWF2ZXN8ZW58MHx8fHwxNzUzNjM1MTYxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'dried tea',
    supplierId: 'sup-2',
    supplierName: 'Golden Grains',
    description: '1kg bag of premium Assam tea leaves, known for its strong and malty flavor.',
    reviews: mockReviews.slice(2,4),
    rating: 4.1,
  },
  {
    id: 'prod-11',
    name: 'Turmeric Powder (500g)',
    category: 'Spices',
    price: 9.50,
    quantity: 120,
    availability: true,
    imageUrl: 'https://images.unsplash.com/photo-1702041295331-840d4d9aa7c9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxUdXJtZXJpYyUyMFBvd2RlciUyMCUyODUwMGclMjl8ZW58MHx8fHwxNzUzNjM1MzYxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'spices powder',
    supplierId: 'sup-2',
    supplierName: 'Golden Grains',
    description: '500g of pure turmeric powder, a staple spice in Indian cuisine for color and flavor.',
    reviews: [],
    rating: 0,
  },
  {
    id: 'prod-12',
    name: 'Notebooks (Pack of 10)',
    category: 'Stationery',
    price: 15.00,
    quantity: 200,
    availability: true,
    imageUrl: 'https://images.unsplash.com/photo-1636014708703-36477b887ee4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxOb3RlYm9va3MlMjAlMjhQYWNrJTIwb2YlMjAxMCUyOXxlbnwwfHx8fDE3NTM2MzUzODN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'notebooks pile',
    supplierId: 'sup-4',
    supplierName: 'Office Essentials',
    description: 'A pack of 10 single-line notebooks, perfect for keeping records and accounts.',
    reviews: [],
    rating: 0,
  },
  {
    id: 'prod-13',
    name: 'Disposable Cups (500 pack)',
    category: 'Packaging',
    price: 14.00,
    quantity: 400,
    availability: true,
    imageUrl: 'https://images.unsplash.com/photo-1750751860244-defb08e07f00?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxEaXNwb3NhYmxlJTIwQ3VwcyUyMCUyODUwMCUyMHBhY2slMjl8ZW58MHx8fHwxNzUzNjM1NDA2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'stacked cups',
    supplierId: 'sup-1',
    supplierName: 'FarmFresh Co.',
    description: 'A pack of 500 disposable paper cups for serving tea, coffee, or water.',
    reviews: [],
    rating: 0,
  },
  {
    id: 'prod-14',
    name: 'Dishwashing Liquid (5L)',
    category: 'Cleaning',
    price: 25.00,
    quantity: 100,
    availability: true,
    imageUrl: 'https://images.unsplash.com/photo-1727233431893-e38a524d7f4b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyMHx8RGlzaHdhc2hpbmclMjBMaXF1aWQlMjAlMjg1THxlbnwwfHx8fDE3NTM2MzU0Mjh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'dishwashing soap',
    supplierId: 'sup-4',
    supplierName: 'Office Essentials',
    description: 'A 5-liter container of concentrated dishwashing liquid with a fresh lemon scent.',
    reviews: [],
    rating: 0,
  },
  {
    id: 'prod-15',
    name: 'Packaged Mango Juice (1L x 6)',
    category: 'Beverage',
    price: 18.00,
    quantity: 80,
    availability: true,
    imageUrl: 'https://images.unsplash.com/photo-1657600704994-ea5020a66231?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMXx8UGFja2FnZWQlMjBNYW5nbyUyMEp1aWNlJTIwJTI4MUwlMjB4JTIwNiUyOXxlbnwwfHx8fDE3NTM2MzU1MTR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'juice carton',
    supplierId: 'sup-1',
    supplierName: 'FarmFresh Co.',
    description: 'A pack of 6 one-liter cartons of delicious and refreshing mango juice.',
    reviews: [],
    rating: 0,
  },
];

export const mockUser: User = {
    id: 'user-1',
    name: 'Taco King',
    email: 'vendor@example.com',
    role: 'vendor',
    avatarUrl: 'https://i.pravatar.cc/150?u=user-1'
};
